/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.40
 * Generated at: 2025-07-17 10:20:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_005fadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/HK_4/BLOCK2/JAVA4/Bai/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ASM1/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1747323223781L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    a.no-underline {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a.no-underline:hover {\r\n");
      out.write("        color: darkblue !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-link {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: block;\r\n");
      out.write("        padding: 5px 0;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-link:hover {\r\n");
      out.write("        color: white;\r\n");
      out.write("        background-color: #f77f2f;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        padding-left: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .account-label:hover {\r\n");
      out.write("        color: darkblue !important;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav style=\"background: linear-gradient(to right, orange, yellow); padding: 15px; display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\" class=\"no-underline\" style=\"color: darkred; font-weight: bold; font-size: 24px;\"> ONLINE ENTERTAINMENT </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"display: flex; align-items: center; gap: 25px;\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favorite\"\r\n");
      out.write("           class=\"no-underline\"\r\n");
      out.write("           style=\"color: blue; font-weight: bold; font-size: 20px;\">\r\n");
      out.write("            HOME\r\n");
      out.write("        </a> \r\n");
      out.write("	</div>\r\n");
      out.write("    <div style=\"position: relative;\">\r\n");
      out.write("	       <span class=\"account-label\"\r\n");
      out.write("	            style=\"color: blue; font-weight: bold; font-size: 20px; cursor: pointer;\"\r\n");
      out.write("	             onmouseover=\"showMenu()\" onmouseout=\"hideMenu()\">\r\n");
      out.write("	             VIDEO\r\n");
      out.write("	      </span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"position: relative;\">\r\n");
      out.write("	       <span class=\"account-label\"\r\n");
      out.write("	            style=\"color: blue; font-weight: bold; font-size: 20px; cursor: pointer;\"\r\n");
      out.write("	             onmouseover=\"showMenu()\" onmouseout=\"hideMenu()\">\r\n");
      out.write("	             USER\r\n");
      out.write("	      </span>\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"position: relative;\">\r\n");
      out.write("	       <span class=\"account-label\"\r\n");
      out.write("	            style=\"color: blue; font-weight: bold; font-size: 20px; cursor: pointer;\"\r\n");
      out.write("	             onmouseover=\"showMenu()\" onmouseout=\"hideMenu()\">\r\n");
      out.write("	             REPORT\r\n");
      out.write("	      </span>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function showMenu() {\r\n");
      out.write("        document.getElementById(\"accountMenu\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function hideMenu() {\r\n");
      out.write("        document.getElementById(\"accountMenu\").style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
